### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by fabifont** [fabifont/buchino#2]

**Comment by Shahzeb-A** [comment]
Hello @fabifont 
Can you describe what kind of help do you need?

**Comment by fabifont** [comment]
> Hello @fabifont
> Can you describe what kind of help do you need?

Hi, I actually finished code documentation.
Now there are two things to do:
- improve docstrings info (wrong/missing info/args/returns). I used google style for docstrings, [here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) you can find a template.
- create a web documentation for the github wiki section with [pdoc](https://github.com/pdoc3/pdoc) or [lazydocs](https://github.com/ml-tooling/lazydocs) or another generator
